#!/bin/bash

# _______           _        _______  _______  ______   _        _______
# (  ____ \|\     /|( (    /|(  ____ \(  ____ \(  ___ \ ( \      (  ____ \
# | (    \/| )   ( ||  \  ( || (    \/| (    \/| (   ) )| (      | (    \/
# | (__    | |   | ||   \ | || |      | (__    | (__/ / | |      | (__
# |  __)   | |   | || (\ \) || |      |  __)   |  __ (  | |      |  __)
# | (      | |   | || | \   || |      | (      | (  \ \ | |      | (
# | )      | (___) || )  \  || (____/\| (____/\| )___) )| (____/\| (____/\
# |/       (_______)|/    )_)(_______/(_______/|/ \___/ (_______/(_______/

# Written by: @Funilrys, Nissar Chababy <contact at funilrys dot com>

############################## Default Values ##################################
# list directory
listDir='tested-list/'

# list name
listName='badreferers.list'

# Output list
outputList=${listDir}${listName}

# Raw list file name
listName='list'

# Hosts file name
hostsFileName='hosts'

# Active directory
activeDir='ACTIVE/'

# Inactive directory
inactiveDir='INACTIVE/'

# Invalid directory
invalidDir='INVALID/'
################################################################################

# Update badrefers.list
curl https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/Pull_Requests_Here_Please/badreferers.list -o ${outputList}

# Create list without the hosts part
if [[ -f ${activeDir}${hostsFileName}  ]]
then
    cat ${activeDir}${hostsFileName} | cut -d ' ' -f2 >> funilrys; mv funilrys ${activeDir}${listName}
fi

# Create list without the hosts part
if [[ -f ${inactiveDir}${hostsFileName}  ]]
then
    cat ${inactiveDir}${hostsFileName} | cut -d ' ' -f2 >> funilrys; mv funilrys ${inactiveDir}${listName}
fi

# Create list without the hosts part
if [[ -f ${invalidDir}${hostsFileName}  ]]
then
    cat ${$invalidDir}${hostsFileName} | cut -d ' ' -f2 >> funilrys; mv funilrys ${$invalidDir}${listName}
fi
