#!/bin/bash

# _______           _        _______  _______  ______   _        _______
# (  ____ \|\     /|( (    /|(  ____ \(  ____ \(  ___ \ ( \      (  ____ \
# | (    \/| )   ( ||  \  ( || (    \/| (    \/| (   ) )| (      | (    \/
# | (__    | |   | ||   \ | || |      | (__    | (__/ / | |      | (__
# |  __)   | |   | || (\ \) || |      |  __)   |  __ (  | |      |  __)
# | (      | |   | || | \   || |      | (      | (  \ \ | |      | (
# | )      | (___) || )  \  || (____/\| (____/\| )___) )| (____/\| (____/\
# |/       (_______)|/    )_)(_______/(_______/|/ \___/ (_______/(_______/

# Written by: @Funilrys, Nissar Chababy <contact at funilrys dot com>
# Github : https://github.com/funilrys/funceble
# Github : https://github.com/funilrys/dead-hosts

################################ Contributors ##################################
#  Let's contribute !!
################################################################################


##################################### Base #####################################
# We get the parent directory which we're gonna call root
root=$(dirname ${PWD})

# We set here the maximal of day between the last generation
maximalDay=5

# Latest dev tool link
toolLink='https://raw.githubusercontent.com/funilrys/funceble/dev/tool'
################################################################################

############################### We move to ${root} #############################
cd ${root}

############################### Date to timestamp ##############################
# Convert date
#
# @CalledBy *
################################################################################
date2stamp () {
    date --utc --date "${1}" +%s
}

############################### Timestamp to date ##############################
# Convert date
#
# @CalledBy *
################################################################################
stamp2date (){
    date --utc --date "1970-01-01 ${1} sec" "+%Y-%m-%d %T"
}

############################### Date Difference ################################
# Get the difference between two dates
#
# @CalledBy *
################################################################################
dateDiff (){
    case ${1} in
        -s)
            sec=1
        ;;
        -m)
            sec=60;
        ;;
        -h)
            sec=3600;
        ;;
        -d)
            sec=86400
        ;;
        *)
            sec=86400
        ;;
    esac
    
    # We convert the given dates
    dte1=$(date2stamp ${1})
    dte2=$(date2stamp ${2})
    diffSec=$((dte2-dte1))
    
    
    if [[ ${diffSec} < 0 ]]
    then
        abs=-1
    else
        abs=1
    fi
    
    echo $((diffSec/sec*abs))
}

################################### Exit Status ################################
# Port funceble status to check-all
#
# @CalledBy *
################################################################################
exitStatus() {
    $("${1}")
    exit $?
}

# We use this to look into every directory and execute an update :)
for directory in *
do
    # We check if the current readed data is a directory
    if [[ -d ${directory} ]]
    then
        # We move into it
        cd ${directory}
        
        percentageFile="${directory}/output/logs/percentage/percentage.txt"
        
        # We check if percentage.txt exist
        if [[ -f "${percentageFile}" ]]
        then
            # We get the date of percentage.txt
            dateOfLastPercentage=$(date -r ${percentageFile})
            
            # We get the difference between now and ${dateOfLastPercentage}
            diffenrenceInDay=$(dateDiff "$(date)" "${dateOfLastPercentage}")
            
            if [[ "${diffenrenceInDay}" -ge ${maximalDay} ]]
            then
                # We get the latest dev tool
                curl -s ${toolLink} -o tool
                
                chown -R travis:travis ${TRAVIS_BUILD_DIR}
                chgrp -R travis ${TRAVIS_BUILD_DIR}
                chmod -R g+rwX ${TRAVIS_BUILD_DIR}
                chmod 777 -Rf ${TRAVIS_BUILD_DIR}/.git
                find ${TRAVIS_BUILD_DIR} -type d -exec chmod g+s '{}' +
                
                # We update the tested-list/*.lists file(s)
                chmod +x update.me && ./update.me
                
                # We update funceble
                ./tool --dev --directory-structure -u -i
                exitStatus "${TRAVIS_BUILD_DIR}/${directory}/funceble --cmd-before-end 'bash ${TRAVIS_BUILD_DIR}/.dev-tools/movetoroot ${directory}' --travis -a -ex --plain --split -h -f tested-list/*.list"
            fi
        else
            # We get the latest dev tool
            curl -s ${toolLink} -o tool
            
            chown -R travis:travis ${TRAVIS_BUILD_DIR}
            chgrp -R travis ${TRAVIS_BUILD_DIR}
            chmod -R g+rwX ${TRAVIS_BUILD_DIR}
            chmod 777 -Rf ${TRAVIS_BUILD_DIR}/.git
            find ${TRAVIS_BUILD_DIR} -type d -exec chmod g+s '{}' +
            
            # We update the tested-list/*.lists file(s)
            chmod +x update.me && ./update.me
            
            # We update funceble
            ./tool --dev --directory-structure -u -i
            exitStatus "${TRAVIS_BUILD_DIR}/${directory}/funceble --cmd-before-end 'bash ${TRAVIS_BUILD_DIR}/.dev-tools/movetoroot ${directory}' --travis -a -ex --plain --split -h -f tested-list/*.list"
        fi
        
        # We move back to ${root}
        cd ${root}
    else
        # We continue our road :)
        continue
    fi
done
