#!/bin/bash

# _______           _        _______  _______  ______   _        _______
# (  ____ \|\     /|( (    /|(  ____ \(  ____ \(  ___ \ ( \      (  ____ \
# | (    \/| )   ( ||  \  ( || (    \/| (    \/| (   ) )| (      | (    \/
# | (__    | |   | ||   \ | || |      | (__    | (__/ / | |      | (__
# |  __)   | |   | || (\ \) || |      |  __)   |  __ (  | |      |  __)
# | (      | |   | || | \   || |      | (      | (  \ \ | |      | (
# | )      | (___) || )  \  || (____/\| (____/\| )___) )| (____/\| (____/\
# |/       (_______)|/    )_)(_______/(_______/|/ \___/ (_______/(_______/

# Written by: @Funilrys, Nissar Chababy <contact at funilrys dot com>
# Github : https://github.com/funilrys/funceble
# Github : https://github.com/funilrys/dead-hosts

################################ Contributors ##################################
#  Let's contribute !!
################################################################################


##################################### Base #####################################
# We get the parent directory which we're gonna call root
root=$(dirname ${PWD})

# We set here the maximal of day between the last generation
maximalDay=5

# Latest dev tool link
toolLink='https://raw.githubusercontent.com/funilrys/funceble/dev/tool'
################################################################################

############################### We move to ${root} #############################
cd ${root}

############################### Date to timestamp ##############################
# Convert date
#
# @CalledBy *
################################################################################
date2stamp () {
    date --utc --date "${1}" +%s
}

############################### Timestamp to date ##############################
# Convert date
#
# @CalledBy *
################################################################################
stamp2date (){
    date --utc --date "1970-01-01 ${1} sec" "+%Y-%m-%d %T"
}

############################### Date Difference ################################
# Get the difference between two dates
#
# @CalledBy *
################################################################################
dateDiff (){
    case ${1} in
        -s)
            sec=1
        ;;
        -m)
            sec=60;
        ;;
        -h)
            sec=3600;
        ;;
        -d)
            sec=86400
        ;;
        *)
            sec=86400
        ;;
    esac
    
    # We convert the given dates
    dte1=$(date2stamp ${1})
    dte2=$(date2stamp ${2})
    diffSec=$((dte2-dte1))
    
    
    if [[ ${diffSec} < 0 ]]
    then
        abs=-1
    else
        abs=1
    fi
    
    echo $((diffSec/sec*abs))
}

################################### Exit Status ################################
# Port funceble status to check-all
#
# @CalledBy *
################################################################################
exitStatus() {
    echo ${1}
    $(bash -x ${1})
    exit $?
}

################################## Start Funceble ##############################
# Start funceble
#
# @CalledBy *
################################################################################
startFunceble(){
    # We get the directory
    local directory="${root}/${1}"
    # We get funceble
    local funcebleToStart="${directory}/funceble"
    # We construct the command before end
    local cmdBeforeEnd="'bash ${root}/.dev-tools/movetoroot \'${1}\''"
    # We contruct tool output
    local toolToStart="${directory}/tool"
    
    # We move into the directory{directory}
    cd ${directory}
    
    # We get the latest dev tool
    curl -s ${toolLink} -o ${toolToStart}
    
    # We update funceble
    ${toolToStart} --dev --directory-structure -u -i
    
    # We change permissions of all files
    chown -R travis:travis ${root}
    chgrp -R travis ${root}
    chmod -R g+rwX ${root}
    chmod 777 -Rf ${root}/.git
    find ${root} -type d -exec chmod g+s '{}' +
    
    # We change permission of funceble
    chmod +x ${funcebleToStart}
    
    # We update the tested-list/*.lists file(s)
    chmod +x update.me && ./update.me
    
    pwd
    ls -al
    
    # We construct the file we have to look
    local fileToLook="$(find ${directory}/tested-list/* -not -name '.keep')"
    
    exitStatus "\"${funcebleToStart}\" \"--cmd-before-end\" \"${cmdBeforeEnd}\" \"--travis\" \"-a\" \"-ex\" \"--plain\" \"--split\" \"-h\" \"-f\" \"${fileToLook}\""
}

# We use this to look into every directory and execute an update :)
for directory in *
do
    # We check if the current readed data is a directory
    if [[ -d ${directory} ]]
    then
        percentageFile="${directory}/output/logs/percentage/percentage.txt"
        
        # We check if percentage.txt exist
        if [[ -f "${percentageFile}" ]]
        then
            # We get the date of percentage.txt
            dateOfLastPercentage=$(date -r ${percentageFile})
            
            # We get the difference between now and ${dateOfLastPercentage}
            diffenrenceInDay=$(dateDiff "$(date)" "${dateOfLastPercentage}")
            
            if [[ "${diffenrenceInDay}" -ge ${maximalDay} ]]
            then
                # We start funceble over the current directory
                startFunceble "${directory}"
            fi
        else
            # We start funceble over the current directory
            startFunceble "${directory}"
        fi
        
        # We move back to ${root}
        cd ${root}
    else
        # We continue our road :)
        continue
    fi
done
