#!/bin/bash

# _______           _        _______  _______  ______   _        _______
# (  ____ \|\     /|( (    /|(  ____ \(  ____ \(  ___ \ ( \      (  ____ \
# | (    \/| )   ( ||  \  ( || (    \/| (    \/| (   ) )| (      | (    \/
# | (__    | |   | ||   \ | || |      | (__    | (__/ / | |      | (__
# |  __)   | |   | || (\ \) || |      |  __)   |  __ (  | |      |  __)
# | (      | |   | || | \   || |      | (      | (  \ \ | |      | (
# | )      | (___) || )  \  || (____/\| (____/\| )___) )| (____/\| (____/\
# |/       (_______)|/    )_)(_______/(_______/|/ \___/ (_______/(_______/

# Written by: @Funilrys, Nissar Chababy <contact at funilrys dot com>
# Github : https://github.com/funilrys/funceble
# Github : https://github.com/funilrys/dead-hosts

################################ Contributors ##################################
#  Let's contribute !!
################################################################################

# Set Some Variables
year=$(date +"%Y")
month=$(date +"%m")
day=$(date +"%d")
timestamp=$(date +"%s")

# Make Sure we are in the Build Directory
cd $TRAVIS_BUILD_DIR

# Create our Version Number
export GIT_TAG=${day}.${month}.${day}.${timestamp}

################################################################################
# Tag our release
################################################################################

git tag ${GIT_TAG} -a -m "${GIT_TAG}"

################################################################################
# Push our commit and tags back to the repo
################################################################################

sudo git push origin master && git push origin master --tags

################################################################################
# Now TravisCI moves into the deploy: section of TravisCI - see .travis.yml
################################################################################
