#!/bin/bash

# _______           _        _______  _______  ______   _        _______
# (  ____ \|\     /|( (    /|(  ____ \(  ____ \(  ___ \ ( \      (  ____ \
# | (    \/| )   ( ||  \  ( || (    \/| (    \/| (   ) )| (      | (    \/
# | (__    | |   | ||   \ | || |      | (__    | (__/ / | |      | (__
# |  __)   | |   | || (\ \) || |      |  __)   |  __ (  | |      |  __)
# | (      | |   | || | \   || |      | (      | (  \ \ | |      | (
# | )      | (___) || )  \  || (____/\| (____/\| )___) )| (____/\| (____/\
# |/       (_______)|/    )_)(_______/(_______/|/ \___/ (_______/(_______/

# Written by: @Funilrys, Nissar Chababy <contact at funilrys dot com>
# GitHub : https://github.com/funilrys/funceble
# GitHub : https://github.com/funilrys/dead-hosts

################################ Contributors ##################################
#  Let's contribute !!
################################################################################

################################################################################
# Move into the build directory
################################################################################
cd $TRAVIS_BUILD_DIR/.dev-tools/

# We get the parent directory which we're gonna call root
root=$(dirname ${PWD})

# We set here the maximal of day between the last generation
maximalDay=5

# Latest dev tool link
toolLink='https://raw.githubusercontent.com/funilrys/funceble/dev/tool'

# Regex ci skip
regexTravis='\[ci\sskip\]'
################################################################################

############################### We move to ${root} #############################
cd ${root}

############################### Date to timestamp ##############################
# Convert date
#
# @CalledBy *
################################################################################
date2stamp ()
{
    date --utc --date "${1}" +%s
}

############################### Timestamp to date ##############################
# Convert date
#
# @CalledBy *
################################################################################
stamp2date ()
{
    date --utc --date "1970-01-01 ${1} sec" "+%Y-%m-%d %T"
}

############################### Date Difference ################################
# Get the difference between two dates
#
# @CalledBy *
################################################################################
dateDiff ()
{
    case ${1} in
        -s)
            sec=1
        ;;
        -m)
            sec=60;
        ;;
        -h)
            sec=3600;
        ;;
        -d)
            sec=86400
        ;;
        *)
            sec=86400
        ;;
    esac
    
    # We convert the given dates
    dte1=$(date2stamp ${1})
    dte2=$(date2stamp ${2})
    diffSec=$((dte2-dte1))
    
    
    if [[ ${diffSec} < 0 ]]
    then
        abs=-1
    else
        abs=1
    fi
    
    echo $((diffSec/sec*abs))
}

############################# Travis Permissions ###############################
# Used to manage/change permissions under travis
#
# @CalledBy startFunceble
################################################################################
travisPermissions()
{
    if [[ ${travisMode} == true ]]
    then
        # We set the permissions to avoid some errors
        chown -R travis:travis ${TRAVIS_BUILD_DIR}
        chgrp -R travis ${TRAVIS_BUILD_DIR}
        chmod -R g+rwX ${TRAVIS_BUILD_DIR}
        chmod 777 -Rf ${TRAVIS_BUILD_DIR}/.git
        find ${TRAVIS_BUILD_DIR} -type d -exec chmod g+s '{}' +
        
        
        if [[ $(git config core.sharedRepository) == '' ]]
        then
            # We make sure that it's right configured
            git config core.sharedRepository group
        fi
    fi
}

################################### Launch Build ###############################
# Commit 'Launch build'
#
# @CalledBy startFunceble
################################################################################
launchBuild()
{
    date > ${root}/.dev-tools/trigger-build && git add --all && git commit -a -m 'Launch build' && git push origin master
}

################################## Start Funceble ##############################
# Start funceble
#
# @CalledBy *
################################################################################
startFunceble()
{
    # We get the directory
    local directory="${root}/${1}"
    # We get funceble
    local funcebleToStart="${directory}/funceble"
    # We contruct tool output
    local toolToStart="${directory}/tool"
    
    echo "${1}" > ${root}/currently_under_test
    
    # We move into the directory{directory}
    cd ${directory}
    
    # We get the latest dev tool
    curl -s ${toolLink} -o ${toolToStart}
    
    # We change permissions of all files
    travisPermissions
    
    # We change the permissions of tool
    chmod +x ${toolToStart}
    
    # We update funceble
    ${toolToStart} --dev --iana --directory-structure -u
    
    # We change permissions of all files
    travisPermissions
    
    # We change permission of funceble
    chmod +x ${funcebleToStart}
    
    if [[ $(git log -1 | tail -1) =~ ${regexTravis} || $(git log -1 | tail -1) =~ Launch\sbuild && ! -f ${directory}/inactive_checked ]]
    then
        # We update the tested-list/*.lists file(s)
        chmod +x update.me && ./update.me
    fi
    
    pwd && ${funcebleToStart} -v
    
    # We construct the file we have to look
    local fileToLook="$(find ${directory}/tested-list/* -not -name '.keep' -not -name '.gitignore')"
    
    # This line should disapear in the future (copyright respect)
    sort -i ${fileToLook} -o ${fileToLook}
    
    # We delete all commented line
    sed -i -r '/^(\s*#|$)/d;' ${fileToLook}
    
    
    if [[ -f ${directory}/inactive_db && ! -f ${directory}/inactive_checked ]]
    then
        sed -i -r '/^(\s*#|$)/d;' ${directory}/inactive_db
        
        # We launch tool
        ${toolToStart} --dev --autosave-minutes 10 --commit-autosave-message "${1} inactive_db - Test" --commit-results-message "${1} inactive_db - Results" -u -i
        
        # We launch funceble
        ${funcebleToStart} --cmd-before-end "bash ${root}/.dev-tools/append_to_original_list" --travis -a -ex --plain --split -h -f "${directory}/inactive_db"
        
        if [[ $(git log -1 | tail -1) =~ ${regexTravis} ]]
        then
            echo "${date}" > ${directory}/inactive_checked
            travisPermissions
            
            launchBuild
        fi
        
        exit 0
        
    else
        ${toolToStart} --dev --autosave-minutes 10 --commit-autosave-message "${1} - Test" --commit-results-message "${1} - Results" -u -i
        ${funcebleToStart} --cmd-before-end "bash ${root}/.dev-tools/copytoroot" --travis -a -ex --plain --split -h -f ${fileToLook}
    fi
    
    if [[ $(git log -1 | tail -1) =~ ${regexTravis} ]]
    then
        if [[ -f ${root}/currently_under_test ]]
        then
            travisPermissions
            rm ${root}/currently_under_test
        fi
        
        if [[ -f ${directory}/inactive_checked ]]
        then
            rm ${directory}/inactive_checked
        fi
        
        date > ${directory}/last_execution_time
       
        travisPermissions
        
        launchBuild
    fi
    
    exit 0
}

if [[ -f ${root}/currently_under_test ]]
then
    currentlyTested="$(head -1 ${root}/currently_under_test)"
    
    find ${root}/${currentlyTested}/ -name 'percentage.txt' -exec rm {} \;
    
    # We start funceble over the current directory
    startFunceble "${currentlyTested}"
else
    if [[ -f ${root}/currently_under_test ]]
    then
        travisPermissions
        rm ${root}/currently_under_test
    fi
    
    # We use this to look into every directory and execute an update :)
    for directory in *
    do
        # We check if the current readed data is a directory
        if [[ -d ${directory} ]]
        then
            executionTimeFile="${directory}/last_execution_time"
            
            # We check if percentage.txt exist
            if [[ -f "${executionTimeFile}" ]]
            then
                # We get the date of percentage.txt
                dateOfLastExecution="$(head -1 ${executionTimeFile})"
                
                # We get the difference between now and ${dateOfLastPercentage}
                diffenrenceInDay=$(dateDiff "$(date)" "${dateOfLastExecution}")
                
                if [[ ${dateOfLastExecution} == 'date' ]]
                then
                   # We manage the case that 'date' has been printed into ${executionTimeFile}
                   diffenrenceInDay=${maximalDay}+2
                fi
                
                if [[ "${diffenrenceInDay}" -ge ${maximalDay} ]]
                then
                    # We start funceble over the current directory
                    startFunceble "${directory}"
                fi
            else
                # We start funceble over the current directory
                startFunceble "${directory}"
            fi
        else
            # We continue our road :)
            continue
        fi
    done
fi
