#!/bin/bash

# _______           _        _______  _______  ______   _        _______
# (  ____ \|\     /|( (    /|(  ____ \(  ____ \(  ___ \ ( \      (  ____ \
# | (    \/| )   ( ||  \  ( || (    \/| (    \/| (   ) )| (      | (    \/
# | (__    | |   | ||   \ | || |      | (__    | (__/ / | |      | (__
# |  __)   | |   | || (\ \) || |      |  __)   |  __ (  | |      |  __)
# | (      | |   | || | \   || |      | (      | (  \ \ | |      | (
# | )      | (___) || )  \  || (____/\| (____/\| )___) )| (____/\| (____/\
# |/       (_______)|/    )_)(_______/(_______/|/ \___/ (_______/(_______/

# Written by: @Funilrys, Nissar Chababy <contact at funilrys dot com>
# GitHub : https://github.com/funilrys/funceble
# GitHub : https://github.com/funilrys/dead-hosts

################################ Contributors ##################################
#  Let's contribute !!
################################################################################

################################################################################
# Move into the build directory
################################################################################
cd $TRAVIS_BUILD_DIR/.dev-tools/

# We get the parent directory which we're gonna call root
root=$(dirname ${PWD})

# We set here the maximal of day between the last generation
maximalDay=5

# Latest dev tool link
toolLink='https://raw.githubusercontent.com/funilrys/funceble/dev/tool'

# Regex ci skip
regexTravis='\[ci\sskip\]'
################################################################################

############################### We move to ${root} #############################
cd ${root}

############################### Date to timestamp ##############################
# Convert date
#
# @CalledBy *
################################################################################
date2stamp () {
    date --utc --date "${1}" +%s
}

############################### Timestamp to date ##############################
# Convert date
#
# @CalledBy *
################################################################################
stamp2date (){
    date --utc --date "1970-01-01 ${1} sec" "+%Y-%m-%d %T"
}

############################### Date Difference ################################
# Get the difference between two dates
#
# @CalledBy *
################################################################################
dateDiff (){
    case ${1} in
        -s)
            sec=1
        ;;
        -m)
            sec=60;
        ;;
        -h)
            sec=3600;
        ;;
        -d)
            sec=86400
        ;;
        *)
            sec=86400
        ;;
    esac
    
    # We convert the given dates
    dte1=$(date2stamp ${1})
    dte2=$(date2stamp ${2})
    diffSec=$((dte2-dte1))
    
    
    if [[ ${diffSec} < 0 ]]
    then
        abs=-1
    else
        abs=1
    fi
    
    echo $((diffSec/sec*abs))
}

################################## Start Funceble ##############################
# Start funceble
#
# @CalledBy *
################################################################################
startFunceble(){
    # We get the directory
    local directory="${root}/${1}"
    # We get funceble
    local funcebleToStart="${directory}/funceble"
    # We contruct tool output
    local toolToStart="${directory}/tool"
    
    echo "${1}" > ${root}/currently_under_test
    
    # We move into the directory{directory}
    cd ${directory}
    
    # We get the latest dev tool
    curl -s ${toolLink} -o ${toolToStart}
    
    # We change permissions of all files
    chown -R travis:travis ${root}
    chgrp -R travis ${root}
    chmod -R g+rwX ${root}
    chmod 777 -Rf ${root}/.git
    find ${root} -type d -exec chmod g+s '{}' +
    
    # We change the permissions of tool
    chmod +x ${toolToStart}
    
    # We update funceble
    ${toolToStart} --dev --iana --directory-structure
    ${toolToStart} --dev --autosave-minutes 10 -u -i
    
    # We change permission of funceble
    chmod +x ${funcebleToStart}
    
    
    # We update the tested-list/*.lists file(s)
    chmod +x update.me && ./update.me
    
    pwd && ${funcebleToStart} -v
    
    # We construct the file we have to look
    local fileToLook="$(find ${directory}/tested-list/* -not -name '.keep' -not -name '.gitignore')"
    
    sort -i ${fileToLook} -o ${fileToLook}
    ${funcebleToStart} --cmd-before-end "bash ${root}/.dev-tools/copytoroot" --travis -a -ex --plain --split -h -f ${fileToLook}
    
    if [[ $(git log | head -5 | tail -1) =~ ${regexTravis} ]]
    then
        git checkout master
        date > ${root}/.dev-tools/trigger-build && git commit -a -m 'Launch build' && git push
    fi
    
    exit 0
}

if [[ -f ${root}/currently_under_test && ! $(git log | head -5 | tail -1) =~ ${regexTravis} && ! $(git log | head -5 | tail -1) =~ Launch\sbuild ]]
then
    rm ${root}/$(head -1 ${root}/currently_under_test)/output/logs/percentage/percentage.txt
    # We start funceble over the current directory
    startFunceble "$(head -1 ${root}/currently_under_test)"
else
    if [[ -f ${root}/currently_under_test ]]
    then
        rm ${root}/currently_under_testd
    fi
    
    # We use this to look into every directory and execute an update :)
    for directory in *
    do
        # We check if the current readed data is a directory
        if [[ -d ${directory} ]]
        then
            percentageFile="${directory}/output/logs/percentage/percentage.txt"
            
            # We check if percentage.txt exist
            if [[ -f "${percentageFile}" ]]
            then
                # We get the date of percentage.txt
                dateOfLastPercentage=$(date -r ${percentageFile})
                
                # We get the difference between now and ${dateOfLastPercentage}
                diffenrenceInDay=$(dateDiff "$(date)" "${dateOfLastPercentage}")
                
                if [[ "${diffenrenceInDay}" -ge ${maximalDay} ]]
                then
                    # We start funceble over the current directory
                    startFunceble "${directory}"
                fi
            else
                # We start funceble over the current directory
                startFunceble "${directory}"
            fi
            
            # We move back to ${root}
            cd ${root}
        else
            # We continue our road :)
            continue
        fi
    done
fi
