#!/bin/bash

# _______           _        _______  _______  ______   _        _______
# (  ____ \|\     /|( (    /|(  ____ \(  ____ \(  ___ \ ( \      (  ____ \
# | (    \/| )   ( ||  \  ( || (    \/| (    \/| (   ) )| (      | (    \/
# | (__    | |   | ||   \ | || |      | (__    | (__/ / | |      | (__
# |  __)   | |   | || (\ \) || |      |  __)   |  __ (  | |      |  __)
# | (      | |   | || | \   || |      | (      | (  \ \ | |      | (
# | )      | (___) || )  \  || (____/\| (____/\| )___) )| (____/\| (____/\
# |/       (_______)|/    )_)(_______/(_______/|/ \___/ (_______/(_______/

# Written by: @Funilrys, Nissar Chababy <contact at funilrys dot com>
# GitHub : https://github.com/funilrys/funceble
# GitHub : https://github.com/funilrys/dead-hosts

################################ Contributors ##################################
#  Let's contribute !!
################################################################################

# Name of the directory to restructure
directoryToRestructure="${1}"

# root directory
root=${TRAVIS_BUILD_DIR}

if [[ ${directoryToRestructure} != '' ]]
then
    toSync=('domains' 'hosts' 'splited' 'HTTP_Analytic')

    for i in ${!toSync[*]}
    do
        if [[ -d ${root}/${directoryToRestructure}/${toSync[${i}]} && -d ${root}/${directoryToRestructure}/output/${toSync[${i}]} ]]
        then
            rsync -avz --delete ${root}/${directoryToRestructure}/output/${toSync[${i}]} ${root}/${directoryToRestructure}/${toSync[${i}]}
            rm -R ${root}/${directoryToRestructure}/output/${toSync[${i}]}
        elif [[ ! -d ${root}/${directoryToRestructure}/${toSync[${i}]} && -d ${root}/${directoryToRestructure}/output/${toSync[${i}]} ]]
        then
            mv ${root}/${directoryToRestructure}/output/${toSync[${i}]} ${root}/${directoryToRestructure}
        fi

        toDelete=('dir-structure' 'funceble' 'iana-domains-db')

        for k in ${!toDelete[*]}
        do
            if [[ -f ${root}/${directoryToRestructure}/${toDelete[${k}]} ]]
            then
                rm ${root}/${directoryToRestructure}/${toDelete[${k}]}
            fi
        done
    done
fi
