#!/bin/bash

# _______           _        _______  _______  ______   _        _______
# (  ____ \|\     /|( (    /|(  ____ \(  ____ \(  ___ \ ( \      (  ____ \
# | (    \/| )   ( ||  \  ( || (    \/| (    \/| (   ) )| (      | (    \/
# | (__    | |   | ||   \ | || |      | (__    | (__/ / | |      | (__
# |  __)   | |   | || (\ \) || |      |  __)   |  __ (  | |      |  __)
# | (      | |   | || | \   || |      | (      | (  \ \ | |      | (
# | )      | (___) || )  \  || (____/\| (____/\| )___) )| (____/\| (____/\
# |/       (_______)|/    )_)(_______/(_______/|/ \___/ (_______/(_______/

# Written by: @Funilrys, Nissar Chababy <contact at funilrys dot com>
# Github : https://github.com/funilrys/funceble
# Github : https://github.com/funilrys/dead-hosts

################################ Contributors ##################################
#  Let's contribute !!
################################################################################


# Set the date
year=$(date +"%Y")
month=$(date +"%m")
day=$(date +"%d")

################################################################################
# Remove Remote Added by TravisCI
################################################################################

git remote rm origin

# **************************
# Add Remote with Secure Key
# **************************

git remote add origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git

################################################################################
# List Remotes ONLY DURING testing - do not do this on live repo / possible key leak
# git remote -v
################################################################################

# *********************
# Set Our Git Variables
# *********************

git config --global user.email "${GIT_EMAIL}"
git config --global user.name "${GIT_NAME}"
git config --global push.default simple

################################################################################
# Make sure we have checked out master branch
################################################################################

git checkout master

################################################################################
# Run funceble to check for dead domains
################################################################################

sudo bash $TRAVIS_BUILD_DIR/.dev-tools/install-run-check-all

################################################################################
# Add all the modified files and commit
################################################################################

git add -A
git commit -am "${GIT_TAG}"

################################################################################
# Travis now moves to the before_deploy: section of .travis.yml
################################################################################
